wixplosives/codux-core

.eslintrc
src/create-simulation.ts

In #4, the return type of `createSimulation` was changed from `any` to `<P>`. This may have unforeseen consequences, so I want to add it back just to be safe.

Replace generic type with 'any' for compatibility 

---

src/types.ts

Remove `LayoutSizeWithAuto` type

Remove "auto" and null value from environment props canvas size

---

packages/react-simulation/LICENSE
packages/react-simulation/README.md
packages/react-simulation/package.json
packages/react-simulation/src/create-simulation.tsx
packages/react-simulation/src/index.ts
packages/react-simulation/src/tsconfig.json
packages/react-simulation/test/create-simulation.spec.tsx
packages/react-simulation/test/fixtures/checkbox-with-wrapper.sim.ts
packages/react-simulation/test/fixtures/checkbox.driver.ts
packages/react-simulation/test/fixtures/checkbox.tsx
packages/react-simulation/test/fixtures/playground.ts
packages/react-simulation/test/fixtures/simulation-fixtures.tsx
packages/react-simulation/test/render-helpers.spec.ts
packages/react-simulation/test/tsconfig.json
packages/simulation-core/LICENSE
packages/simulation-core/README.md
packages/simulation-core/package.json
packages/simulation-core/src/create-metadata.ts
packages/simulation-core/src/create-renderable-base.ts
packages/simulation-core/src/create-simulation-base.ts
packages/simulation-core/src/index.ts
packages/simulation-core/src/plugins/css-vars-plugin.tsx
packages/simulation-core/src/plugins/tags-plugin.ts
packages/simulation-core/src/render-helpers.tsx
packages/simulation-core/src/tsconfig.json
packages/simulation-core/src/types.ts
tsconfig.json

Introduce `@wixc3/simulation-core` and `@wixc3/react-simulation` containing the changes of 2.1.0-2.2.0 separated into the different packages.

feat: generic simulations via @wixc3/simulation-core and @wixc3/react-simulation

---

packages/react-simulation/test/setup-stage.spec.tsx
packages/simulation-core/src/create-renderable-base.ts
packages/simulation-core/src/index.ts
packages/simulation-core/src/setup-stage.tsx
packages/simulation-core/src/types.ts
tsconfig.json

Refactor `simulation.setupStage` function.
- Enable passing a parent element as a container for the canvas element.
- return `updateCanvas` and `updateWindow` functions for manipulating `window` and `canvas` styles in addition to the `canvas` element and `cleanup` function.
-  Change the canvas dimensions once vertical/horizontal margins are applied.

refactor: setup-stage

---

packages/board-core/package.json
packages/board-plugins/package.json
packages/react-board/package.json
packages/react-board/src/create-board.tsx
packages/react-board/src/index.ts
packages/react-board/src/types.ts

This will publish these packages.
Also added a re-export for `BoardSetupFunction` in react-board

BREAKING!: remove private: true from packages

---

packages/board-core/src/setup-stage.tsx
packages/board-core/src/types.ts

- Fixed not resetting `windowBackgroundColor` if it was removed from `environmentProps`
- Remove occurrence of `backgroundColor` through `previousWindowEnvironmentProps` because it's not in use anymore
- Remove occurrence of `backgroundColor` through `canvasStyle` because it's not in use anymore

fix(board-core): Removing window/canvas default background-colors

---

.eslintrc
.github/workflows/tests.yml
package.json
packages/board-core/src/create-renderable-base.ts
packages/board-core/src/types.ts
packages/board-plugins/test/react-context-plugin.spec.ts
packages/react-board/src/create-board.tsx
packages/react-board/src/react-error-handled-render.tsx
packages/react-board/test/setup-stage.spec.tsx
webpack.config.js
yarn.lock

to fully support `react@18`, we need to use the new API: https://reactjs.org/docs/react-dom-client.html#createroot
using it requires two breaking changes:
1. board's render() fn now returns the cleanup callback, rather than it being a separate fn (that expected a container).
2. import to `react-dom/client` requires remapping (`fallback: {'react-dom/client': false}`) when used alongside react 16/17. runtime code polyfills it, but the import still needs to be handled.
made sure we know rendering ended using onMount hook via `ErrorBoundry` instead of a third render() parameter (which doesn't exist in createRoot).
also:
- ensure CI tests react@17 as well
- refactor cleanup code in tests to use createDisposbles and properly remove test container from body.

feat!: use React's new createRoot API

---

packages/react-board/src/react-error-handled-render.tsx

related https://github.com/wixplosives/codux/issues/12211
When render fails and error cannot be intercepted with safe render it will throw error and renderer will never provide cleanup function for container `() => ReactDOM.unmountComponentAtNode(container)`. Only in React@17 broken render will leave internal _reactRootContainer object on container DOM node that will  result into empty renders (see videos from the issue).
React@18 does not have this issue.
Fix: clean up container node when such error occurs.
https://user-images.githubusercontent.com/9338713/211033885-f9d30cc5-bd91-4020-9873-a0cae43f51d3.mov
Note: I tried to figure out implementation intent here with error boundary and rejecting the promise as much as I could. I implemented the fix in a way that it does not change the …

fix(react-board): react 17, cleanup stage element when render failed outside safe render

---

packages/react-board/src/react-error-handled-render.tsx
packages/react-board/test/error-handling.spec.ts
packages/react-board/test/fixtures/throwing-on-click.board.tsx
packages/react-board/test/fixtures/throwing.board.tsx

In `react@18`, errors weren't rejected correctly in `reactErrorHandledRendering`, leading to an inconsistent flow within the `ErrorBoundary` component. The incorrect flow involved the sequence of `getDerivedStateFromError` -> `componentDidMount` -> `componentDidCatch`.
This resulted in `this.props.onRender` (which resolves the render Promise) being invoked before `this.props.reportError` (which should reject the Promise).
To resolve this issue, I made sure `onRender` is called only when no error is present. This ensures that the error rejection is executed appropriately, providing a more reliable error handling mechanism within `reactErrorHandledRendering`.

fix(react-board): error handling in react@18

---

packages/react-board/README.md
packages/react-board/src/content-slot.tsx
packages/react-board/src/index.ts

add a `ContentSlot` component which will be used in boards to wrap the actual content(s) of the board.
usually a componnet

feat: add ContentSlot component

---

packages/board-core/src/setup-stage.tsx

The stage doesn't get updated when applying the "0" value for margin or padding sides (`top` for example).

fix(board-core): allow applying 0 for board environments props

---

packages/react-board/src/types.ts

Adding `readyToSnapshot` property, so user can configure the delay for thumbnail snapshot

feat(react-board): Add readyToSnapshot prop to IReactBoard

---

packages/board-core/src/setup-stage.tsx
packages/board-core/src/types.ts
packages/react-board/test/setup-stage.spec.tsx

The Canvas functionality is being deprecated. 
This PR removes the following functionalities in Codux:
1. Canvas cannot be edited from the stage or the Board Settings panel.
2. Canvas will not be centered on stage.
3. Pre-defined canvas related environment props will not take effect.
Changes include:
- Deprecation of the canvas environment properties.
- Removal of the functionality of editing the canvas.  
- Removal of the styles from body and the canvas.

feat!: remove canvas style and editing capabilities

---

packages/react-board/src/content-slot.tsx

Following a talk with @alisey, this change should provide a way to differentiate one content slot from another when processed in Codux. 🥷🏼

feat(content-slot): wrap children in a div with data attribute

---

packages/react-board/src/variant.tsx

Currently, it is the same as `ContentSlot`, just a different name and data attribute.

feat(react-board): add `Variant` component

---

packages/app-core/src/define-app-types.ts
packages/define-remix-app/src/define-remix-app.tsx
packages/define-remix-app/src/index.ts
packages/define-remix-app/src/page-template.ts
packages/define-remix-app/test/define-remix.spec.ts

This PR enhances the "Generate New Page" flow by introducing both validation and normalization steps.
**Validations:**
- Ensure the component name starts with an english letter, as it must be capitalized and valid as the first character of a JavaScript identifier.
- Validate that the route is not empty.
- Restrict route parameters to contain only english letters and underscores for the first character, and allow numbers for subsequent characters.
- Validate that the route contains only characters that are safe to use in file and folder names on the file system.
- Added a test to confirm the existing validation that prevents overriding the home route.
**Normalization:**
- Remove `<>{}` from the initial JSX content.
- Strip any non-identifier characters from the component name.

fix(define-remix-app): validate and normalize new page

---

packages/define-remix-app/src/define-remix-app.tsx

Handling cases where the passed URI starts with a forward slash.
NOTE
Tests should be added in a different PR using a suite for running define-remix-app in the browser.

fix(define-remix-app): supports navigation to URIs starting with '/'

---

packages/app-core/src/define-app-types.ts
packages/define-remix-app/src/define-remix-app.tsx
packages/define-remix-app/src/remix-app-utils.ts
packages/define-remix-app/test/define-remix.spec.ts

This PR adds routing pattern configuration to the `getNewPageInfo` and `getMovePageInfo` functions result, enabling Codux to correctly handle file locations when needed.
Notice that the possible patterns were originally defined as part of `define-remix-app`, but moved to the base `define-app-types` and might need to be expended later to allow more patterns from other frameworks.

feat(app-core): provide routing pattern in new / moved page results

---

packages/define-remix-app/src/define-remix-app.tsx
packages/define-remix-app/test/define-remix.spec.ts

This PR updates the routes sorting logic according to the readable name without taking the path segments amount into account.
This change results in a more intuitive and clearer page order within Codux.
**Before:**
**After:**
Notice the previous sorting logic was written for some reason, but there was no comments explaining it and no tests were broken after changing it 🤷🏻

fix(remix-app): sort routes by readable name

---

package-lock.json
packages/app-core/package.json
packages/define-remix-app/package.json
packages/react-board/package.json

prereleases are not included by default for >=18.0.0
define-remix-app uses same range as current remix

feat: allow react@19.0.0-rc.0 in peer range

---

packages/define-remix-app/src/define-remix-app.tsx
packages/define-remix-app/src/manifest-to-router.tsx
packages/define-remix-app/src/remix-app-utils.ts

Quick fix to make sure server method call to `loader` is serialized in the same way calls to `action` are.
In addition also add unknown fields to the `serialize/deserialize` utility functions.

fix(remix-app): serialize and deserialize both loader and  action

---

packages/define-remix-app/src/manifest-to-router.tsx

Making sure that passing synchronous data will not throw an error when rendered inside react.lazy

fix(define-remix-app): wrap lazy component render with Suspense

---

packages/define-remix-app/src/manifest-to-router.tsx
packages/define-remix-app/src/page-template.ts

We used to initialize the navigation method when the RootComponent renders, now we initialize it when we start on an error boundary as well (where RootComp isn't rendered).
Also fixed the dynamic page template.

fix(define-remix-app): apply navigation method when starting from an error boundary

---

packages/define-remix-app/src/page-template.ts
packages/define-remix-app/test/define-remix.spec.ts

This PR resolves an issue where a page name containing `$` would cause problems. The newly created component name is now normalized to remove the invalid `$` character, ensuring it adheres to valid naming conventions.

fix(remix-app): remove $ from page comp name

---

packages/define-remix-app/src/page-template.ts

use `LoaderFunctionArgs`instead of an inline object and destructure params on usage.

fix(define-remix-app): fix page template to include an import to the LoaderFunctionArgs interface

---

packages/app-core/test-kit/index.ts
packages/define-remix-app/src/manifest-to-router.tsx
packages/define-remix-app/test/define-remix.spec.ts
packages/define-remix-app/test/test-cases/roots.ts

This PR makes sure both page and root components are updated when a page/root module updates.
The solution here is to update the data using the [Remix revlalidator api](https://remix.run/docs/en/main/hooks/use-revalidator) each time a page/root module is changed without knowing if the loader actually changed.
Additionally, an option was added to the test driver to prevent automatic re-renders during the 
`prepareApp -> onManifestUpdate` call in order to validate that module update invalidates the loaders with no external integration.

feat(define-remix-app): update loader on change

---

packages/app-core/src/define-app-types.ts
packages/app-core/src/define-app.tsx
packages/app-core/test-kit/index.ts
packages/define-remix-app/src/define-remix-app.tsx
packages/define-remix-app/src/manifest-to-router.tsx
packages/define-remix-app/src/remix-app-utils.ts
packages/define-remix-app/test/define-remix.spec.ts
packages/define-remix-app/test/test-cases/roots.ts

allowed adding extraData on the root of the manifest
used this extra data for all rendering information
support of API only routes

moved extra data to root to enable supporting fetchers from api routes

---

packages/define-remix-app/src/define-remix-app.tsx
packages/define-remix-app/src/manifest-to-router.tsx
packages/define-remix-app/src/navigation.ts

This PR changes the navigation to include the `search` and the `hash` alongside `pathname` in the navigation uri.

support navigation to hash url

---

packages/define-remix-app/src/define-remix-app.tsx

This pull request adds and exports a `GetStaticRoutes` type to enhance clarity and type safety in user projects when utilizing the `getStaticRoutes` method.

feat(define-remix-app): export GetStaticRoutes type for better clarity

---

packages/app-core/src/define-app-types.ts
packages/app-core/src/define-app.tsx

Aligning both generic types for the `IAppManifest` interface  (manifest's `extraData` and route's `extraData`) to be `unknown` when not provided.

fix: align manifest generic types to use `unknown`

---

packages/define-remix-app/src/define-remix-app.tsx

Fixed error text for invalid start to new page name.

ux(define-remix-app): update new page name error text

---

packages/define-remix-app/src/define-remix-app.tsx
packages/define-remix-app/test/define-remix.spec.ts

This PR fixes an incorrect error message for new page names that start with an underscore (_). 
Previously, entering a name like `_page` would incorrectly trigger the message:
> "Page name cannot be empty." 
Now, the message accurately reflects the input: 
> "Page names must start with a letter of the alphabet."

fix(define-remix-app): invalid input with initial underscore

---

packages/define-remix-app/src/manifest-to-router.tsx
packages/define-remix-app/test/define-remix.spec.ts
packages/define-remix-app/test/test-cases/route-builder.ts

This PR makes sure that an `ErrorBoundary` is rendered within the defined `Layout` of the `root` route.

fix(define-remix-app): render root layout when error boundary is rendered

---

packages/codux-ui/src/image/image.tsx
packages/codux-ui/src/image/types.ts

This PR makes sure that most of the `img` props which are not handled by the `WixImage` component itself are passed to the img element.
It also refactors the `picture` use with `source` and `img` element to a purely `img` element usage

feat(codux-ui): pass props and refactor picture to img

---

packages/define-remix-app/src/defer.ts
packages/define-remix-app/src/define-remix-app.tsx
packages/define-remix-app/src/manifest-to-router.tsx
packages/define-remix-app/src/remix-app-utils.ts
packages/define-remix-app/test/define-remix.spec.ts
packages/define-remix-app/test/test-cases/route-builder.ts

This PR adds proper support for Remix's `defer` feature in both `loader` and `action` functions. 
Previously, deferred responses were handled by awaiting promises on the server and passing the resolved, unwrapped data to the client. However, this approach did not align with Remix's intended behavior, which is to pass promises to the client within loader data. Additionally, the existing tests did not verify this behavior.
In this solution, we still await the data on the server, but we now mark it as deferred data, including information about specific fields expected to be deferred. On the client side, these fields are re-wrapped as resolved or rejected promises, ensuring that the client receives them in a deferred state as Remix requires.

feat(define-remix-app): handle remix defer
